name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: Format (rustfmt)
        run: cargo fmt --all -- --check

      - name: Lint (clippy)
        run: cargo hack --workspace --feature-powerset clippy --all-targets -- -D warnings

      - name: Test
        run: cargo hack --workspace --feature-powerset test
